# Generated by Django 3.0.5 on 2020-04-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200429_0504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='updates',
            new_name='updated',
        ),
    ]
