# Generated by Django 3.0.5 on 2020-05-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200430_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dummy_field',
            field=models.CharField(default='Dummy Field', max_length=90),
        ),
    ]
