# Generated by Django 3.0.5 on 2020-05-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dummy_field',
        ),
    ]
